config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'welcome#index'

  resources :users, only: [:index, :new, :create, :destroy, :edit, :update]

  resources :schedules, only: [:index, :create, :new]

  resources :backoffice, only: [:index]

  resources :welcome, only: [:index]

  resources :services, only: [:index, :new, :create, :destroy, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates  :owner_name, :owner_email, :phone, :date, :hour, presence: true

  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_attached_file :imagem, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/s

  validates  :name, :description, :price, presence: true

  has_many :schedule
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index

  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_user!

  def index
    render :index
  end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :authenticate_user!, only: [:index]

  def index
    @schedule = without_past
    render :index
  end

  def new
    @schedule = Schedule.new
    render :new
  end

  def create
    @schedule = Schedule.new schedule_params
    if @schedule.save
      ScheduleMailer.with(schedule: @schedule).schedule_email.deliver_now
      flash[:notice] = "Serviço agendado com sucesso"
      redirect_to root_path
    else
      flash[:notice] = "Falha ao agendar serviço tente novamente"
      render :new
    end
  end

  private

  def without_past
    Schedule.where("date >= ?", Date.current)
  end

  def schedule_params
    params.require(:schedule).permit(:owner_name, :owner_email, :phone,  :date, :hour, :service_id)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_service, only: [:edit, :update, :destroy]

  def index
    @service = Service.all
    render :index
  end

  def create
    @service = Service.new service_params
    if @service.save
      flash[:notice] = "Serviço salvo com sucesso"
      redirect_to services_path
    else
      flash[:notice] = "Falha ao salvar serviço"
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @service.update  service_params
      flash[:notice] = 'Serviço atualizado com sucesso'
      redirect_to services_path
    else
      flash[:notice] = 'Falha ao atualizar serviço'
      render :edit
    end
  end

  def destroy
    if @service.destroy
      flash[:notice] = 'Serviço excluído com sucesso'
      redirect_to services_path
    else
      flash[:notice] = 'Falha ao excluído com sucesso'
      redirect_to services_path
    end
  end

  def new
    @service = Service.new
    render :new
  end

  private

  def service_params
    params.require(:service).permit(:name, :description, :price, :imagem)
  end

  def set_service
    @service = Service.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "Usuário criado com sucesso"
      redirect_to users_path
    else
      flash[:notice] = "Falha ao criado com sucesso"
      redirect_to users_path
    end
  end

  def edit
    render :edit
  end

  def update
    if @user.update  user_params
      flash[:notice] = 'Usuário atualizado com sucesso'
      redirect_to users_path
    else
      flash[:notice] = 'Falha ao atualizar dados do usuário'
      redirect_to users_path
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'Usuário excluído'
      redirect_to users_path
    else
      flash[:notice] = 'Falha ao excluir usuário'
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @services = Service.all
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/schedule_controller_helper.rb
module ScheduleControllerHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/backoffice/_background.html.erb
<section class="back-image-backoffice mt-5">

</section>

app/views/backoffice/_footer.html.erb
<section class="footer">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center">
      <%= link_to 'Deslogar', destroy_user_session_path, method: :delete, class: 'btn-font btn btn-dark' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mt-1">
      <p class="text-center">Desenvolvido por: Zaparoli Técnologias de E-commerce LTDA</p>
    </div>
  </div>
</section>

app/views/backoffice/_header.html.erb
  <div class="header-backoffice">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">Área Administrativa Pet's Dreams</h1>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 btn-group d-flex justify-content-center">
        <div class="col-md-2">
          <%= link_to 'Serviços', '/services', class:'btn-font btn btn-success' %>
        </div>
        <div class="col-md-2">
          <%= link_to 'Usuários', '/users', class: 'btn-font btn btn-warning' %>
        </div>
        <div class="col-md-2">
          <%= link_to 'Serviços Agendados', '/schedules', class: 'btn-font btn btn-info' %>
        </div>
    </div>
  </div>
</div>

app/views/backoffice/index.html.erb
<%= render partial: 'backoffice/header' %>
<div class="container">
  <div class="row mt-5">
    <div class="col-md-12 d-flex justify-content-center">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <h1 class="text-center">Bem vindo a área do administrador</h1>
      <h5 class="text-center">Aqui você poderá cadastrar, alterar e excluir serviços e usuários, além de obter acesso a relatórios sobres
      os serviços agendados que são atualizados em tempo real.</h5>
    </div>
  </div>
</div>
<%= render partial: 'backoffice/background' %>
<%= render partial: 'backoffice/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-3 col-md-6 offset-3 d-flex justify-content-center">
      <%= form_for @schedule do |f| %>

        <div class="field form-group">
          <label>Nome do Dono</label>
          <%= f.text_field :owner_name, class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <label>Email</label>
          <%= f.email_field :owner_email, class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <label>Telefone</label>
          <%= f.text_field :phone, class: 'form-control', required: true%>
        </div>

        <div class="field form-group">
          <label>Data</label>
          <%= f.date_field :date, class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <label>Hora</label>
          <%= f.time_field :hour, class: 'form-control', required: true %>
        </div>


          <%= f.hidden_field :service_id, value: params[:service], class: 'form-control' %>

        <div>
          <%= f.submit acao , class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/_schedule.html.erb
<tr>
  <td> <%= schedule.owner_name %> </td>
  <td> <%= schedule.owner_email %> </td>
  <td> <%= schedule.phone %> </td>
  <td> <%= schedule.date.strftime("%d/%m/%Y") %> </td>
  <td> <%= schedule.hour %> </td>
  <td> <%= schedule.service.name %> </td>
</tr>

app/views/schedules/index.html.erb
<%= render "backoffice/header" %>
<div class="container mt-4">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Área de agendamentos</h1>
      <p class="text-center">Nessa área você pode verificar todos os serviços que estão agendados</p>
    </div>
  </div>

  <table class="table table-striped table-dark text-center">
    <thead>
    <tr>
      <th class="text-center">Dono do Pet</th>
      <th class="text-center">Email do Dono</th>
      <th class="text-center">Telefone</th>
      <th class="text-center">Dia</th>
      <th class="text-center">Horario</th>
      <th class="text-center">Serviço</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'schedule', collection: @schedule %>
    </tbody>
  </table>
</div>

<%= render "backoffice/background" %>
<%= render "backoffice/footer" %>

app/views/schedules/new.html.erb
<%= render 'welcome/header' %>
<div class="row mt-5">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="col-md-12">
    <h1 class="display text-center">Agendar novo serviço</h1>
    <p class="text-center">Após o agendamento você irá receber um e-mail em até 24 horas com os dados de confirmação do agendamento</p>
  </div>
  <div class="col-md-12 d-flex justify-content-center">
    <%= render partial: 'form', locals: {acao: 'Agendar novo serviço' } %>
  </div>
</div>
<%= render 'welcome//background' %>
<%= render 'welcome/footer' %>

app/views/services/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <%= form_for @service do |f| %>

        <div class="form-group">
          <label>Nome do Serviço</label>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <label>Descrição</label>
          <%= f.text_area :description, class: 'form-control', rows: 4, required: true %>
        </div>

        <div class="form-group col-md-1 p-0">
          <label for="">Preço</label>
          <%= f.number_field :price, step: 0.01, class: 'form-control', required: true %>
        </div>

        <div class="form-group col-md-4 p-0">
          <label for="">Imagem</label>
          <%= f.file_field :imagem, class: 'form-control', required: true %>
        </div>

        <%= f.submit acao, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/services/_service.html.erb
<tr>
  <td><%= service.name %></td>
  <td><img src="<%= service.imagem.url(:thumb) %>" alt=""></td>
  <td>R$ <%= service.price %></td>
  <td>
    <%= button_to "Remover Serviço", service, method: :delete, class: 'btn btn-danger' %>
  </td>
  <td>
    <%= link_to "Alterar", edit_service_path(service), class: 'btn btn-primary btn-font' %>
  </td>
</tr>

app/views/services/edit.html.erb
<%= render partial: 'backoffice/header' %>

<div class="row mt-5">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="col-md-12 d-flex justify-content-center">
    <h1 class="display text-center">Edição de um serviço</h1>
  </div>
  <div class="col-md-12 d-flex justify-content-center">
    <%= render partial: 'form', locals: { acao: 'Alterar serviço' } %>
  </div>
</div>

<%= render partial: 'backoffice/background' %>

<%= render partial: 'backoffice/footer' %>

app/views/services/index.html.erb
<%= render "backoffice/header" %>
<div class="container mt-4">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Área de serviços</h1>
      <p class="text-center">Nessa área você poder cadastrar, alterar ou excluir serviços, acesse a edição de serviços
      para mais detalhes e descrição do mesmo.</p>
    </div>
  </div>

  <table class="table table-striped table-dark text-center">
    <thead>
    <tr>
      <th class="text-center">Nome do serviço</th>
      <th class="text-center">Imagem</th>
      <th class="text-center">Preço</th>
      <th class="text-center">Remover</th>
      <th class="text-center">Editar</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'service', collection: @service %>
    </tbody>
  </table>

  <div>
    <%= link_to 'Novo Serviço', new_service_path, class: 'btn btn-info btn-font' %>
  </div>
 </div>

<%= render "backoffice/background" %>

<%= render partial: 'backoffice/footer' %>

app/views/services/new.html.erb
<%= render partial: 'backoffice/header' %>

<div class="row mt-5">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="col-md-12">
    <h1 class="display text-center">Cadastrar novo Serviço</h1>
  </div>
  <div class="col-md-12 d-flex justify-content-center">
    <%= render partial: 'form', locals: { acao: 'Criar novo serviço' } %>
  </div>
</div>

<%= render partial: 'backoffice/background' %>

<%= render partial: 'backoffice/footer' %>

app/views/users/_form.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-3 col-md-6 offset-3 d-flex justify-content-center">
      <%= form_for @user do |f| %>

        <div class="field form-group">
          <label>Email</label>
          <% if @user.email == 'admin@admin' %>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', disabled: true %>
          <% else %>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', required: true %>
          <% end %>
        </div>

        <div class="field form-group">
          <label>Senha</label>
          <%= f.password_field :password, autocomplete: "Senha", class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <label>Confirmar Senha</label>
          <%= f.password_field :password_confirmation, autocomplete: "Senha", class: 'form-control', required: true %>
        </div>

        <div>
          <%= f.submit acao , class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_sign_up.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-3 col-md-6 offset-3 d-flex justify-content-center">
      <%= form_for @user, :url => {:action => "create"} do |f| %>

        <div class="field form-group">
          <label>Email</label>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
        </div>

        <div class="field form-group">
          <label>Senha</label>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "Senha", class: 'form-control' %>
        </div>

        <div class="field form-group">
          <label>Confirmar Senha</label>
          <%= f.password_field :password_confirmation, autocomplete: "Senha", class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit "Cadastar", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
 <tr>
    <td><%= users.email %></td>
   <td>
     <% if users.email == 'admin@admin' %>
       <p>Não é possível excluir o administrador</p>
     <% else %>
       <%= button_to "Excluir Usuário", users, method: :delete, class: 'btn btn-danger'%>
     <% end %>
   </td>
   <td>
    <%= link_to "Editar usuário", edit_user_path(users), class: 'btn btn-primary btn-font' %>
    </td>
  </tr>

app/views/users/edit.html.erb
<%= render "backoffice/header" %>
<div class="row">
  <div class="col-md-12 d-flex justify-content-center">
    <h1 class="display text-center">Editar usuário</h1>
  </div>
  <div class="col-md-12 d-flex justify-content-center">
    <%= render partial: 'form', locals: { acao: 'Editar usuário' } %>
  </div>
</div>
<%= render "backoffice/background" %>

<%= render partial: 'backoffice/footer' %>

app/views/users/index.html.erb
<%= render "backoffice/header" %>
<div class="container mt-4">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Área de controle de usuários</h1>
    </div>
  </div>
  <table class="table table-striped table-dark text-center">
    <thead>
    <tr>
      <th class="text-center">Email</th>
      <th class="text-center">Remover</th>
      <th class="text-center">Editar</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'users', collection: @users %>
    </tbody>
  </table>

  <div>
    <%= link_to 'Novo Usuário', new_user_path, class: 'btn btn-info btn-font' %>
  </div>
</div>

<%= render "backoffice/background" %>

<%= render partial: 'backoffice/footer' %>

app/views/users/new.html.erb
<%= render "backoffice/header" %>
<div class="row mt-5">
  <div class="col-md-12">
    <h1 class="display text-center">Cadastrar novo usuário</h1>
  </div>
  <div class="col-md-12 d-flex justify-content-center">
    <%= render partial: 'form', locals: {acao: 'Criar novo usuário' } %>
  </div>
</div>
<%= render "backoffice/background" %>

<%= render partial: 'backoffice/footer' %>

app/views/welcome/_background.html.erb
<section class="back-image mt-5">

</section>

app/views/welcome/_footer.html.erb
<section class="footer">
  <div class="row">
    <div class="offset-md-5 col-md-2 offset-md-5">
      <%= link_to 'Área do Administrador', backoffice_index_path, class: 'btn-font btn btn-dark' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mt-1">
      <p class="text-center">Desenvolvido por: Zaparoli Técnologias de E-commerce LTDA</p>
    </div>
  </div>
</section>

app/views/welcome/_header.html.erb
<div class="header">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Bem Vindo ao Pet's Dreams</h1>
      <h4 class="text-center">Pet's Dreams é o maior e melhor conceitudo petshop da américa latina, com os melhores produtos e técnicas, venha conhecer!</h4>
    </div>
    <div class="col-md-12 d-flex justify-content-center">
      <%= link_to 'Inicio', root_path, class: 'btn-font btn btn-success' %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render partial: 'header' %>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Conheça alguns de nossos serviços</h1>
      <p class="text-center">Tem alguém que te faz sorrir após um dia exaustivo? Alguém que está com você mesmo quando ninguém
      mais está? Pois é, esse alguém é seu pet! E ele não merece nada menos que um atendimento dos sonhos, então venha conheçer o pet's dreams,
      o maior petshop da américa latina, com os melhores profissionais, equipamentos e produtos de alta qualidade. Um verdadeiro sonho para seu pet.</p>
    </div>
  </div>
  <div class="row">
    <% @services.try(:each) do |service| %>
      <div class="col-md-4 col-sm-12 col-xs-12">
        <div class="card mt-3">
          <img class="card-img-top img-fluid card-image" src="<%= service.imagem.url(:medium) %>" alt="Foto do Serviço">
          <div class="card-body">
            <h4 class="card-title text-center"><%= service.name %></h4>
            <p class="text-center"> <%= service.description %></p>
            <h5>Valor R$ <%= service.price %></h5>
            <%= link_to 'Agendar Serviço', new_schedule_path(service: service), class: 'btn btn-danger btn-font' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>



<%= render partial: 'background' %>

<%= render partial: 'footer' %>